let stockProductos = [
    {id: 1, titulo: "Camara dahua 2mpx exterior", link:"pages/c1.html",tipo: "Camara", cantidad: 1, marca: "DAHUA", precio: 21200,
     descripcion: "<ul><li>caracteristica 1</li><li>caracteristica 2</li></ul>", img: 'img/C1.webp'},
    {id: 2, titulo: "Camara dahua 2mpx domo int.", link:"pages/c1.html", tipo: "Camara", cantidad: 1, marca: "DAHUA", precio: 22200, 
    descripcion: "Descripcion", img: 'img/C2.webp'},
    {id: 3, titulo: "DVR Dahua XVR4104",  link:"pages/c1.html",tipo: "Equipo", cantidad: 1, marca: "DAHUA", precio: 31200, 
    descripcion: "Descripcion", img: 'img/E1.webp'},
    {id: 4, titulo: "DVR Dahua XVR4108", link:"pages/c1.html", tipo: "Equipo", cantidad: 1, marca: "HIKVISION", precio: 21400, 
    descripcion: "Descripcion", img: 'img/E1.webp'},
    {id: 5, titulo: "Camara Dahua 5mpx 360", link:"pages/c1.html", tipo: "Accesorios", cantidad: 1, marca: "DAHUA", precio: 21200,
     descripcion: "Descripcion", img: 'img/E2.webp'},
    {id: 6, titulo: "Camara Hikvision 3mpx", link:"pages/c1.html", tipo: "Accesorios", cantidad: 1, marca: "HIKVISION", precio: 21500,
     descripcion: "Descripcion", img: 'img/C3.webp'},
     {id: 7, titulo: "DVR Dahua XVR4108", link:"pages/c1.html", tipo: "Equipo", cantidad: 1, marca: "HIKVISION", precio: 21400, 
     descripcion: "Descripcion", img: 'img/E1.webp'},
     {id: 8, titulo: "Camara Dahua 5mpx 360", link:"pages/c1.html", tipo: "Accesorios", cantidad: 1, marca: "DAHUA", precio: 21200,
      descripcion: "Descripcion", img: 'img/E2.webp'},
     {id: 9, titulo: "Camara Hikvision 3mpx", link:"pages/c1.html", tipo: "Accesorios", cantidad: 1, marca: "HIKVISION", precio: 21500,
      descripcion: "Descripcion", img: 'img/C3.webp'},
   ]